config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'posts#index'
  resources :posts
  resources :users, only:[:index, :show ,:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '観光地' },
    { id: 3, name: '川越土産' },
    { id: 4, name: 'レストラン・カフェ' },
    { id: 5, name: 'ファッション・雑貨' },
    { id: 6, name: '体験' },
    { id: 7, name: 'イベント' },
    { id: 8, name: 'サービス・その他' },
    { id: 9, name: '該当なし' }
  ]
  include ActiveHash::Associations
  has_many :users
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :text
    validates :image
  end
  validates :category_id, numericality: { other_than: 1, message: 'を選択してください' }

  belongs_to :user
  has_one_attached :image
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]
  include ActiveHash::Associations
end

app/models/user.rb
class User < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'が無効です' }
    validates :introduction
    validates :address
    validates :business_hour
    validates :image
  end

  validates :password, presence: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: ' は半角英数字の両方を含めてください' }
  validates :category_id, numericality: { other_than: 1, message: ' を選択してください' }

  has_many :posts
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :category_id, :introduction, :url, :business_hour, :address, :latitude, :longitude, :phone_number, :image])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, _password|
      username == ENV['BASIC_AUTH_USER'] && ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :destroy]

  def index
    @posts = Post.all.order('created_at DESC')
    @posts = Post.includes(:user)
    @posts = Post.page(params[:page]).per(8)
    @post = Post.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'posts/new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render root_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless @post.user_id == current_user.id
  end

  def post_params
    params.require(:post).permit(:title, :category_id, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :destroy]

  def index
    @users = User.all.order(id: :DESC).page(params[:page]).per(5)
  end

  def show
    @posts = @user.posts
    @posts = Post.order('created_at DESC')
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user.id)
      sign_in(current_user, bypass: true)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to root_path
    else
      render root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :category_id, :introduction, :url, :business_hour, :address, :latitude, :longitude, :phone_number, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def contributor_confirmation
    redirect_to action: :index unless @user.id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coedo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel = "preconnect" href = "https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div class="footer">
      <p class="copyright">Copyright © coedo.</p>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="user-post">
  <div class="card-main">
    <div class="card-main-img">
      <%= image_tag post.image, class: :"card-img" %>
    </div>
    <div class="card-main-topic">
      <div class="topic-date">
        <%=l post.created_at, format: :short %>
      </div>
      <%= link_to "#{post.title}",post_path(post.id), class: :card__title %>
      <p class="card__summary">
        <%= simple_format"#{post.text}" %>
      </p>
      <div class="post-edit-destroy">
        <% if user_signed_in? && current_user.id == post.user_id %>
          <%= link_to '投稿編集', edit_post_path, class: "post-edit" %>
          <%= link_to '削除', post_path, method: :delete, class:'post-destroy' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "shared/header"%>
<%= form_with(model: @post,class: 'new-post-main', local: true)do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        投稿編集
      </h1>
    </div>
    <p class="required-item">必須項目※</p>
    <%=render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">title※</label>
      </div>
      <%= f.text_area :title, class:"input-default", id:"title" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">カテゴリー※</label>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">テキスト※</label>
      </div>
      <%= f.text_area :text, class:"input-text", id:"text", placeholder:"例) 投稿記事" %>
    </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">画像</label>
    </div>
    <%= f.file_field :image, class:"post-image", id:"post-image" %>
  </div>
    <div class='post-btn'>
      <%= f.submit "編集する" ,class:"post-gray-btn" %>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <header>
      <%= render "shared/header" %>
    </header>

    
    <div class="top-wrapper">
      <div class ="main-container">
        <h1>お気に入りのcoedoを見つけよう。</h1>
      </div>
    </div>

    <div class="topic-wrapper">
      <div class="topic-container">
        <div class="heading">
          <h1>TOPICS</h1>
        </div>
        <div class="topics-list">
          <ul class="topics">
            <% @post.each do |post|%>
              <li class='list'>
              <%=link_to post_path(post.id) do%>
                <div class="post-img-content">
                  <%=image_tag post.image, class: "post-img" %>
                </div>
                <div class="post-time">
                  <%=l post.created_at, format: :short%>
                </div>
                <div class="post-title-content">
                  <h3 class="post-title">
                    <%=post.title%>
                  </h3>
                </div>
              <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <%= paginate @posts %>
    </div>
    <div class="message-wrapper">
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<%= render "shared/header"%>
<%= form_with model: @post, url: posts_path, method: :POST, class: 'new-post-main', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        新規投稿
      </h1>
    </div>
    <p class="required-item">必須項目※</p>
    <%=render 'shared/error_messages', model: f.object %>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">title※</label>
      </div>
      <%= f.text_area :title, class:"input-default", id:"title" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">カテゴリー※</label>
      </div>
      <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">テキスト※</label>
      </div>
      <%= f.text_area :text, class:"input-text", id:"text", placeholder:"例) 投稿記事" %>
    </div>
    <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">画像※</label>
    </div>
    <%= f.file_field :image, class:"post-image", id:"post-image" %>
  </div>
    <div class='post-btn'>
      <%= f.submit "投稿する" ,class:"post-gray-btn" %>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="close-btn">
    <%= link_to image_tag("back-btn.png", class:"close_btn"), :back %>
  </div>
  <div class="inner">
    <div class="topic-date">
      <%= l @post.created_at, format: :short %>
    </div>
    <div class="topic-title">
      <%= @post.title%>
    </div>

    <div class="topic-main">
      <%= link_to "#{@post.user.nickname}", user_path(@post.user.id), class: :topic_user %>
      <div class="topic-section-img">
        <div class="img-block">
          <%= image_tag @post.image,class:"topic-img" %>
        </div>
      </div>
      <div class="topic-section-text">
        <div class="topic-text">
          <%= simple_format(@post.text) %>
        </div>
      </div>
      <div class="post-edit-destroy">
        <% if user_signed_in? && current_user.id == @post.user_id %>
          <%= link_to '投稿編集', edit_post_path, class: "post-edit" %>
          <%= link_to '削除', post_path, method: :delete, class:'post-destroy' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<head>
<style type="text/css">
<!--
a:link { color:#333; text-decoration:none }
a:visited { color:#333; text-decoration:none }
a:hover { color:#333; text-decoration:none }
a:active { color:#333; text-decoration:none }
-->
</style>
</head>

<body>
  <header>
    <div class='container'>
      <div class="header-logo">
        <%= link_to 'coedo', root_path, class:'coedo-icon' %>
      </div>
      <div class='nav'>
          
        <ul class='nav-lists'>
          <li><%= link_to 'ユーザー一覧', users_path,class:"users-index" %></li>
          <% if user_signed_in? %>
            <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
            <li><%= link_to '新規投稿', new_post_path ,class: "new-post" %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>
</body>

app/views/users/_map.html.erb
<script type="text/javascript">
  function initMap() {
// #latitude,longitudeから位置を特定
    var test ={lat: <%= user.latitude %>, lng: <%= user.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= user.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

//  #Map上の指定した位置にピンを挿して表示する
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                 });

     marker.addListener('click', function() {
       infowindow.open(map, marker);
     });
  }
</script>

<script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>

<style type="text/css">
  #map { height: 200px;
         width: 80%;}
</style>

<%# #mapの表示 %>
<div id="map"></div>

app/views/users/edit.html.erb
<%= render "shared/header" %>
<div class="registration-main">
<%= form_for(current_user) do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>
  <p class="required-item">必須項目※</p>
  <%=render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前※</label>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) 川越太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">プロフィール写真※</label>
    </div>
    <%= f.file_field :image, class:"shop-image", id:"shop-image" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス※</label>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード※</label>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)※</label>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">カテゴリー※</label>
    </div>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"category"}) %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">紹介文※</label>
    </div>
    <%= f.text_area :introduction, class:"input-default-introduction", id:"introduction", placeholder:"例) 店舗紹介(300文字まで)",rows:"7" , maxlength:"300" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">URL</label>
    </div>
    <%= f.text_area :url, class:"input-default", id:"url" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">営業時間・定休日※</label>
    </div>
    <%= f.text_area :business_hour, class:"input-default-business_hour", id:"business_hour", placeholder:"例) 営業時間：10:00~18:00 定休日:毎週月曜日" %>
  </div>
  
  <%# ▼住所/電話番号登録 %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">住所※</label>
    </div>
    <%= f.text_field :address, class:"input-default", id:"address", placeholder:"埼玉県川越市○○町"%>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">電話番号※</label>
    </div>
    <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <%# ▲住所/電話番号登録 %>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "変更する" ,class:"register-gray-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>
</div>

app/views/users/index.html.erb
<%= render "shared/header" %>
<div class="main-users-index">
  <div class="users-container">
    <h3 class="users-heading">coedoの専門店一覧</h3>
    <% @users.each do |user|%>
      <div class="users-index-item">
        <div class="user-left">
          <%= image_tag user.image,class:"user-index-img" %>
        </div>
        <div class="user-right">
          <div class="user-right-name">
            <%= link_to "#{user.nickname}", user_path(user.id) %>
          </div>
          <div class="user-right-introduction">
            <%= user.introduction%>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<%# ▼店舗概要 %>
<div class="user-show">
  <div class="user-box">
    <h2 class ="name">
      <%= @user.nickname%>
    </h2>
    <div class="user-img-content">
      <%= image_tag @user.image,class:"user-box-img"%>
    </div>

    <div class="user-introduction">
      <p class="introduction-detail"><%= simple_format(@user.introduction) %></p>
    </div>

    <% if user_signed_in? && current_user.id == @user.id %>
      <%= link_to 'ユーザー編集', edit_user_path, class:"user-edit" %>
      <%= link_to 'ユーザー削除', user_path, method: :delete, class:"user-destory" %>
    <% end %>

    <div class="user-info">
      <table class="detail-tabel">
        <tbody class="fistChild-lastChild">
          <tr class="firstChild">
            <th class="detail-user">カテゴリー</th>
            <td class="detail-value"><%= @user.category.name %></td>
          </tr>
          <tr class="firstChild">
            <th class="detail-user">TEL</th>
            <td class="detail-value"><%= @user.phone_number %></td>
          </tr>
          <tr class="firstChild">
            <th class="detail-user">住所</th>
            <td class="detail-value"><%= @user.address %></td>
          </tr>
          <tr class="firstChild">
            <th class="detail-user">オフィシャルサイト</th>
            <td class="detail-value"><%= raw Rinku.auto_link(h(@user.url)) %></td>
          </tr>
          <tr class="firstChild">
            <th class="detail-user">営業時間・定休日</th>
            <td class="detail-value"><%= @user.business_hour %></td>
          </tr>
        </tbody>
      </table>
      <div class="map">
        <%= render partial: "map", locals: { user: @user } %>
      </div>
    </div>
    <h3 class="card-heading">
      ニュース
    </h3>
    <div class="user__card">
      <%= render partial:'posts/post', collection: @user.posts %>
    </div>
  </div>
</div>
<%# ▲店舗概要 %>